branches:
  only:
  - master
sudo: required
dist: bionic
mono: none
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/stable
install:
- sudo snap alias dotnet-sdk.dotnet dotnet
- dotnet --version
- dotnet restore
script:
- dotnet build
- dotnet test Uploadcare.Tests/Uploadcare.Tests.csproj
