branches:
  only:
  - master
language: csharp
dist: trusty
mono: none
dotnet: 3.0.1
install:
- dotnet restore
script:
- dotnet build
- dotnet test UploadcareCSharp.Tests/UploadcareCSharp.Tests.csproj
