branches:
  only:
  - master
sudo: required
dist: xenial
mono: none
dotnet: 3.0.101
install:
- dotnet restore
script:
- dotnet build
- dotnet test UploadcareCSharp.Tests/UploadcareCSharp.Tests.csproj
